//
// New component for displaying cuisine suggestions generated by the AI.
//

import React from 'react';

interface CuisineSuggestionsProps {
  suggestions: string[];
  onSelect: (cuisine: string) => void;
  onClose: () => void;
  isLoading: boolean;
}

const Spinner = () => (
    <svg className="animate-spin h-8 w-8 text-accent-gold" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    </svg>
);

const CuisineSuggestions: React.FC<CuisineSuggestionsProps> = ({ suggestions, onSelect, onClose, isLoading }) => {
  return (
    <div className="absolute inset-0 z-30 bg-black/60 flex items-center justify-center animate-fade-in-up" style={{animationDuration: '0.3s'}}>
      <div className="card w-full max-w-md m-4 p-6 text-center">
        <button onClick={onClose} className="absolute top-3 right-3 text-gray-500 hover:text-white transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
        </button>
        <h2 className="text-xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-yellow-300 to-orange-400 mb-4">今天想吃哪一類？</h2>
        
        {isLoading ? (
            <div className="flex justify-center items-center h-48">
                <Spinner />
            </div>
        ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            {suggestions.map((cuisine) => (
              <button
                key={cuisine}
                onClick={() => onSelect(cuisine)}
                className="p-4 bg-white/5 hover:bg-white/10 rounded-lg text-white font-semibold transition-all duration-200 ease-out transform hover:scale-105"
              >
                {cuisine}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default CuisineSuggestions;
